### ISSUE TITLE
Error opening query log file after deploying bundle.yaml

### ISSUE THREAD

**Issue by Iulian7** [prometheus-operator/prometheus-operator#3239]
**What did you do?**
1. Deployed `bundle.yaml` v0.39.0. I only changed the namespace from `default` to `monitoring` in the `Service`, `ServiceAccount` and `Deployment`. I also changed the namespace of the service account subject in the `ClusterRoleBinding`. This all went fine.  
2. Created a `Prometheus` resource in the same namespace. Looking at the logs from the newly created `prometheus` pod, I see:
```
level=error ts=2020-05-21T13:05:58.949Z caller=query_logger.go:87 component=activeQueryTracker msg="Error opening query log file" file=/prometheus/queries.active err="open /prometheus/queries.active: permission denied"
```

Another error that shows up is:
```
level=error ts=2020-05-21T13:06:03.29076534Z caller=runutil.go:98 msg="function failed. Retrying in next tick" err="trigger reload: reload request failed: Post http://localhost:9090/-/reload: dial tcp 127.0.0.1:9090: connect: connection refused"
```

**Did you expect to see some different?**
Yes - I expected it to create a running `Prometheus` resource. 

**Environment**
Deployed to GKE (Kubernetes version 1.16.8-gke.15), `VPC-native enabled`, `Private cluster disabled`, `Workload Identity enabled`, 

* Prometheus Operator version:

    `v0.39.0`
    

* Kubernetes version information:

    `1.16.8`
    

* Kubernetes cluster kind:

    GKE

* Manifests:

Prometheus resource definition:
```
        apiVersion: "monitoring.coreos.com/v1",
        kind: "Prometheus",
        metadata: {
            "name": "prometheus",
            "namespace": "monitoring",
        },
        spec: {
            replicas: 1,
            retention: "2d",
            remoteWrite: [
                {
                    url: "URL",
                    basicAuth: {
                        username: {key: "username", name: "secret"},
                        password: {key: "password", name: "secret"},
                    },
                },
            ],
            storage: {
                volumeClaimTemplate: {
                    spec: {
                        storageClassName: "ssd", // the storage class exists I checked. 
                        accessModes: ["ReadWriteOnce"],
                        resources: {requests: {storage: "200G"}},
                    },
                },
            },
            resources: {
                requests: {
                    memory: "4G",
                    cpu: "2",
                },
            },
            scrapeInterval: "10s",
        }
```

* Prometheus Operator Logs:

```
E0521 11:56:48.528842       1 reflector.go:178] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:478: Failed to list *v1.ServiceMonitor: servicemonitors.monitoring.coreos.com is forbidden: User "system:serviceaccount:monitoring:prometheus-operator" cannot list resource "servicemonitors" in API group "monitoring.coreos.com" at the cluster scope
E0521 11:56:53.079560       1 reflector.go:178] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:480: Failed to list *v1.PrometheusRule: prometheusrules.monitoring.coreos.com is forbidden: User "system:serviceaccount:monitoring:prometheus-operator" cannot list resource "prometheusrules" in API group "monitoring.coreos.com" at the cluster scope
E0521 11:56:57.953855       1 reflector.go:178] github.com/coreos/prometheus-operator/pkg/thanos/operator.go:312: Failed to list *v1.ConfigMap: configmaps is forbidden: User "system:serviceaccount:monitoring:prometheus-operator" cannot list resource "configmaps" in API group "" at the cluster scope
E0521 11:56:59.468282       1 reflector.go:178] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:479: Failed to list *v1.PodMonitor: podmonitors.monitoring.coreos.com is forbidden: User "system:serviceaccount:monitoring:prometheus-operator" cannot list resource "podmonitors" in API group "monitoring.coreos.com" at the cluster scope
E0521 11:57:02.704247       1 reflector.go:178] github.com/coreos/prometheus-operator/pkg/alertmanager/operator.go:216: Failed to list *v1.Alertmanager: alertmanagers.monitoring.coreos.com is forbidden: User "system:serviceaccount:monitoring:prometheus-operator" cannot list resource "alertmanagers" in API group "monitoring.coreos.com" at the cluster scope
E0521 11:57:06.782754       1 reflector.go:178] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:482: Failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:monitoring:prometheus-operator" cannot list resource "secrets" in API group "" at the cluster scope
E0521 11:57:08.819379       1 reflector.go:178] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:477: Failed to list *v1.Prometheus: prometheuses.monitoring.coreos.com is forbidden: User "system:serviceaccount:monitoring:prometheus-operator" cannot list resource "prometheuses" in API group "monitoring.coreos.com" at the cluster scope
E0521 11:57:09.971031       1 reflector.go:178] github.com/coreos/prometheus-operator/pkg/alertmanager/operator.go:217: Failed to list *v1.StatefulSet: statefulsets.apps is forbidden: User "system:serviceaccount:monitoring:prometheus-operator" cannot list resource "statefulsets" in API group "apps" at the cluster scope
E0521 11:57:12.807554       1 reflector.go:178] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:483: Failed to list *v1.StatefulSet: statefulsets.apps is forbidden: User "system:serviceaccount:monitoring:prometheus-operator" cannot list resource "statefulsets" in API group "apps" at the cluster scope
E0521 11:57:14.021070       1 reflector.go:178] github.com/coreos/prometheus-operator/pkg/thanos/operator.go:311: Failed to list *v1.ThanosRuler: thanosrulers.monitoring.coreos.com is forbidden: User "system:serviceaccount:monitoring:prometheus-operator" cannot list resource "thanosrulers" in API group "monitoring.coreos.com" at the cluster scope
E0521 11:57:14.331828       1 reflector.go:178] github.com/coreos/prometheus-operator/pkg/thanos/operator.go:313: Failed to list *v1.PrometheusRule: prometheusrules.monitoring.coreos.com is forbidden: User "system:serviceaccount:monitoring:prometheus-operator" cannot list resource "prometheusrules" in API group "monitoring.coreos.com" at the cluster scope
E0521 11:57:18.318305       1 reflector.go:178] github.com/coreos/prometheus-operator/pkg/thanos/operator.go:318: Failed to list *v1.StatefulSet: statefulsets.apps is forbidden: User "system:serviceaccount:monitoring:prometheus-operator" cannot list resource "statefulsets" in API group "apps" at the cluster scope
E0521 11:57:23.784327       1 reflector.go:178] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:484: Failed to list *v1.Namespace: namespaces is forbidden: User "system:serviceaccount:monitoring:prometheus-operator" cannot list resource "namespaces" in API group "" at the cluster scope
E0521 11:57:24.831246       1 reflector.go:178] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:481: Failed to list *v1.ConfigMap: configmaps is forbidden: User "system:serviceaccount:monitoring:prometheus-operator" cannot list resource "configmaps" in API group "" at the cluster scope
level=info ts=2020-05-21T11:58:02.028330408Z caller=operator.go:171 component=alertmanageroperator msg="successfully synced all caches"
level=info ts=2020-05-21T11:58:07.628356894Z caller=operator.go:407 component=prometheusoperator msg="successfully synced all caches"
level=warn ts=2020-05-21T11:58:07.628516869Z caller=operator.go:1227 component=prometheusoperator msg="neither serviceMonitorSelector nor podMonitorSelector specified. Custom configuration is deprecated, use additionalScrapeConfigs instead"
level=info ts=2020-05-21T11:58:07.628645965Z caller=operator.go:1122 component=prometheusoperator msg="sync prometheus" key=monitoring/prometheus
level=info ts=2020-05-21T11:58:08.17868753Z caller=operator.go:1122 component=prometheusoperator msg="sync prometheus" key=monitoring/prometheus
level=info ts=2020-05-21T11:58:08.325796542Z caller=operator.go:1122 component=prometheusoperator msg="sync prometheus" key=monitoring/prometheus
level=info ts=2020-05-21T11:58:08.356869873Z caller=operator.go:1122 component=prometheusoperator msg="sync prometheus" key=monitoring/prometheus
level=info ts=2020-05-21T11:58:09.681962049Z caller=operator.go:1122 component=prometheusoperator msg="sync prometheus" key=monitoring/prometheus
level=info ts=2020-05-21T11:58:15.328528844Z caller=operator.go:256 component=thanosoperator msg="successfully synced all caches"
```

The Prometheus logs are: 
```
level=info ts=2020-05-21T13:31:26.954Z caller=main.go:333 msg="Starting Prometheus" version="(version=2.17.2, branch=HEAD, revision=18254838fbe25dcc732c950ae05f78ed4db1292c)"
level=info ts=2020-05-21T13:31:26.954Z caller=main.go:334 build_context="(go=go1.13.10, user=root@9cb154c268a2, date=20200420-08:27:08)"
level=info ts=2020-05-21T13:31:26.954Z caller=main.go:335 host_details="(Linux 4.19.109+ #1 SMP Mon Mar 16 06:27:01 PDT 2020 x86_64 prometheus-prometheus-0 (none))"
level=info ts=2020-05-21T13:31:26.954Z caller=main.go:336 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2020-05-21T13:31:26.954Z caller=main.go:337 vm_limits="(soft=unlimited, hard=unlimited)"
level=error ts=2020-05-21T13:31:26.954Z caller=query_logger.go:87 component=activeQueryTracker msg="Error opening query log file" file=/prometheus/queries.active err="open /prometheus/queries.active: permission denied"
panic: Unable to create mmap-ed active query log

goroutine 1 [running]:
github.com/prometheus/prometheus/promql.NewActiveQueryTracker(0x7ffdcf5a95ce, 0xb, 0x14, 0x2dcaa20, 0xc0006f8660, 0x2dcaa20)
	/app/promql/query_logger.go:117 +0x4cd
main.main()
	/app/cmd/prometheus/main.go:364 +0x5245
```

**Anything else we need to know?**:

**Comment by brancz** [comment]
That's curious. Could you check the permissions and owner on that file? I would have expected the kubelet to have changed ownership before mounting. This is a GCP type volume I assume?

**Comment by shouichi** [comment]
Had the same issue and setting `securityContext` worked for me. See https://github.com/prometheus-operator/prometheus-operator/issues/3459.

**Comment by simonpasquier** [comment]
Closing in favor of #3459
