### ISSUE TITLE
prometheus-operator crash on a Probe 

### ISSUE THREAD

**Issue by kehao95** [prometheus-operator/prometheus-operator#3517]
**What happened?**
I didn't fully understand the [API of Probe](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#probe) especially the difference between `prober` and `targets`  so I decided to try it out and I composed an (may be invalid) probe.yaml and applied. 
prometheus-operator crashed when I applied the `Probe.yaml`

**Did you expect to see something different?**

Some error output telling that was an invalid `probe.spec`
Or at least don't crash prometheus-operator.

**How to reproduce it (as minimally and precisely as possible)**:

```yaml
# kubectl apply -f test-probe.yaml
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata: 
  namespace: monitoring
  name: test-probe
spec: 
  jobName: test-prob-name
  prober:
    url: https://www.example.com # was using my app url
    scheme: http
    path: /v1/health
  interval: 15s
```
delete the Probe then the prometheus-operator can run again

**Environment**

* Prometheus Operator version:

    I've tried `v0.41.1` and `v0.42.0` so far. They all crash on this.

* Kubernetes version information:

    ```
    Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0",  GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
    Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-gke.401", GitCommit:"eb94c181eea5290e9da1238db02cfef263542f5f", GitTreeState:"clean", BuildDate:"2020-09-09T00:57:35Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
    ```

* Kubernetes cluster kind:

    GKE `v1.16.13-gke.401`

* Manifests:

   see above `test-probe.yaml`

* Prometheus Operator Logs:

```
 prometheus-operator level=info ts=2020-09-19T03:59:33.234581106Z caller=operator.go:1203 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
 prometheus-operator panic: runtime error: invalid memory address or nil pointer dereference
 prometheus-operator [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x146be35]
 prometheus-operator goroutine 194 [running]:
 prometheus-operator github.com/coreos/prometheus-operator/pkg/prometheus.(*configGenerator).generateProbeConfig(0xc0002524a0, 0x2, 0x14, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
 prometheus-operator     /home/travis/gopath/src/github.com/coreos/prometheus-operator/pkg/prometheus/promcfg.go:709 +0x525
 prometheus-operator github.com/coreos/prometheus-operator/pkg/prometheus.(*configGenerator).generateConfig(0xc0002524a0, 0xc0009f5a78, 0xc000f21500, 0xc000f215f0, 0xc000f21770, 0xc0006b4600, 0xc0006b4630, 0x0, 0x0, 0x0, ...
 prometheus-operator     /home/travis/gopath/src/github.com/coreos/prometheus-operator/pkg/prometheus/promcfg.go:284 +0xde3
 prometheus-operator github.com/coreos/prometheus-operator/pkg/prometheus.(*Operator).createOrUpdateConfigurationSecret(0xc000156400, 0xc0009f5a78, 0xc0011336e0, 0x1, 0x1, 0x0, 0x0)
 prometheus-operator     /home/travis/gopath/src/github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:1798 +0x4d3
 prometheus-operator github.com/coreos/prometheus-operator/pkg/prometheus.(*Operator).sync(0xc000156400, 0xc0011b7b40, 0xe, 0x0, 0x0)
 prometheus-operator     /home/travis/gopath/src/github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:1209 +0x333
 prometheus-operator github.com/coreos/prometheus-operator/pkg/prometheus.(*Operator).processNextWorkItem(0xc000156400, 0x0)
 prometheus-operator     /home/travis/gopath/src/github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:1096 +0xf0
 prometheus-operator github.com/coreos/prometheus-operator/pkg/prometheus.(*Operator).worker(0xc000156400)
 prometheus-operator     /home/travis/gopath/src/github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:1085 +0x2b
 prometheus-operator created by github.com/coreos/prometheus-operator/pkg/prometheus.(*Operator).Run
 prometheus-operator     /home/travis/gopath/src/github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:509 +0x298
 prometheus-operator stream closed

```

**Anything else we need to know?**:

It would be nice if we can have an example for `probe` and explain how should we use `prober`. So know i guess a `blackbox_exporter` is good right? Then we might at least mention `blackbox_exporter` for that

**Comment by lilic** [comment]
Thanks for the bug report, seems like a valid bug. Are you interested in working on the fix?

**Comment by kehao95** [comment]
> Thanks for the bug report, seems like a valid bug. Are you interested in working on the fix?

I wish I can, but sorry I'm new to golang and k8s.

**Comment by lilic** [comment]
@kehao95 no worries!

**Comment by liguozhong** [comment]
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: testprobename
  namespace: arms-prom
spec:
  jobName: testprobejob
  module: http_401
  prober:
    scheme: http
    url: localhost:9335
    path: /blackbox/probe
  targets:
    staticConfig:
      static:
        - https://www.baidu.com
        - https://www.taobao.com
