### ISSUE TITLE
AMZeroDowntimeRollingDeployment e2e test failed on MacBook with M1 chip

### ISSUE THREAD

**Issue by heylongdacoder** [prometheus-operator/prometheus-operator#5012]
**What happened?**

AMZeroDowntimeRollingDeployment e2e test failed on MacBook with M1 chip

**Did you expect to see something different?**

Yes. Expect AMZeroDowntimeRollingDeployment e2e test success on MacBook with M1 chip.

**How to reproduce it (as minimally and precisely as possible)**:

By using Prometheus Operator latest main branch, run `make test-e2e` on MacBook with M1 chip. 

**Environment**

* Docker information:

```
Client:
 Cloud integration: v1.0.28
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:04:45 2022
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.11.0 (83626)
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:01 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:30:46Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-19T15:42:59Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/arm64"}
```

* KinD version:

`kind v0.14.0 go1.18.2 darwin/arm64`

* Kubernetes cluster kind:

`kind create cluster`

* `make test-e2e` logs:

```
=== RUN   TestAllNS/x/AMZeroDowntimeRollingDeployment
    alertmanager_test.go:566: waiting for service alertmanager-webhook to become ready timed out: timed out waiting for the condition
--- FAIL: TestAllNS (334.21s)
    --- FAIL: TestAllNS/x (300.08s)
        --- FAIL: TestAllNS/x/AMZeroDowntimeRollingDeployment (300.08s)
```

* `alertmanager-webhook` pod image:

`quay.io/coreos/prometheus-alertmanager-test-webhook:latest`

* `alertmanager-webhook` pod status:

```
allns-x-amzerodowntimerollingdeployment-ri395v-0   alertmanager-webhook-78b9fd4cf5-4dvdf                   0/1     CrashLoopBackOff   3 (50s ago)   101s
```

* `alertmanager-webhook` pod logs: 

```
runtime: failed to create new OS thread (have 2 already; errno=22)
fatal error: newosproc

runtime stack:
runtime.throw(0x6884d4, 0x9)
	/usr/local/go/src/runtime/panic.go:596 +0x95
runtime.newosproc(0xc420026000, 0xc420036000)
	/usr/local/go/src/runtime/os_linux.go:163 +0x18c
runtime.newm(0x696d78, 0x0)
	/usr/local/go/src/runtime/proc.go:1628 +0x137
runtime.main.func1()
	/usr/local/go/src/runtime/proc.go:126 +0x36
runtime.systemstack(0x7b8c00)
	/usr/local/go/src/runtime/asm_amd64.s:327 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1132

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:281 fp=0xc420022788 sp=0xc420022780
runtime.main()
	/usr/local/go/src/runtime/proc.go:127 +0x6c fp=0xc4200227e0 sp=0xc420022788
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc4200227e8 sp=0xc4200227e0
```

**Anything else we need to know?**:

**Comment by simonpasquier** [comment]
Thanks for flagging this! Indeed the e2e tests depend on https://quay.io/repository/coreos/prometheus-alertmanager-test-webhook which has never been migrated when we switched from the coreos organization. And I suspect that we have the same issue with `quay.io/coreos/instrumented-sample-app` :-/
In practice, we'd need to [build](https://github.com/prometheus-operator/prometheus-operator/blob/main/scripts/push-docker-image.sh) & push the images to the quay.io/prometheus-operator org instead.

**Comment by simonpasquier** [comment]
@heylongdacoder if you have some time, maybe you can try #5025 on your local environment?

**Comment by heylongdacoder** [comment]
> @heylongdacoder if you have some time, maybe you can try #5025 on your local environment?

Hi @simonpasquier , I have confirmed that image `quay.io/prometheus-operator/prometheus-alertmanager-test-webhook:latest` is running fine on my local environment! Thank you so much for fixing this. :D
